### ISSUE TITLE
search/replace box goes away if you use any arrow keys

### ISSUE THREAD

**Issue by hywUMD** [whitphx/vscode-emacs-mcx#360] opened 2020-07-09 02:07 UTC
I know quite some issues are on the list. But this one is really important because search/replace is being used a lot. I find it frustrating that you can't use arrow keys to navigate through the target text in the replace text field box. Please try to give this issue some of your value time and efforts. 

In the end, thank you for providing such a great extension.

**Comment by tuttieee** [comment] 2020-07-09 02:52
That's an intended behavior. See #71 .

If you don't like it, you can disable it by setting your own `keybindings.json` like below:
```json
[
{
    "key": "right",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "left",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "up",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "down",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+f",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+b",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+p",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+n",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+a",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+e",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
}
]
```

**Comment by hywUMD** [comment] 2020-07-09 03:34
Thank you very much for looking at this and I am sorry that I created that issue without going through thoroughly previous issues to see if that had been raised before.

So since that design is intentional, I am willing to work with the correct design. Just one thing: any suggestions how I should move around to edit target text in the replace widget?

Best regards!

**Comment by mrcoles** [comment] 2020-08-17 20:35
@tuttieee thanks for sharing! In case anyone else wants the find widget to remain open after pressing “enter”, then you can add the following to your keybindings overrides (which overrides a different command):

```json
  {
    "key": "enter",
    "command": "-closeFindWidget",
    "when": "editorFocus && findWidgetVisible"
  }
```

**Comment by krid** [comment] 2020-09-11 03:26
I filed a feature request with VSCode (see above) that I think would allow something much closer to the Emacs experience.  Hopefully it'll get traction before the heat death of the universe.

**Comment by tuttieee** [comment] 2020-10-03 12:56
@krid 
I fixed not to close the widget when you are using replace input.
See https://github.com/tuttieee/vscode-emacs-mcx/pull/428/files .
You can use `replaceInputFocussed` context in addition to `findWidgetVisible`.
It's not published, but I found it from VSCode's source.

**Comment by ANorwell** [comment] 2020-10-12 22:00
Emacs actually doesn't behave like this, exactly. I tested it in vanilla emacs:

- Searches (C-s) are interrupted by any navigation (arrow keys, M-b, whatever). (However, if you move focus to the minibuffer by clicking on it, now navigation will move around the minibuffer)
- Query replaces (M-%) move the focus to the minibuffer immediately, and any navigation navigates within the minibuffer.

So to match emacs functionality, searches (C-s) would have to behave differently from query replaces (M-%). I wonder if that's actually possible, given that vscode seems to treat searches and "query replaces" as the same thing? The hotkeys above disable it for both. 

For what it's worth, I find this fairly annoying. When you actually _want_ to edit a complicated query replacement, there's no great way to navigate -- you have to use the mouse. But I also like the emacs functionality for regular searches.

It might be possible to do this with `replaceInputFocussed`? I'll play with it.

**Comment by ANorwell** [comment] 2020-10-13 11:57
The reason the manual keybindings above didn't work, I believe, is because when you remove a keybinding, it has to be for the same `when` conditional. The following keybinding changes worked for me:

```
      {
        "key": "right",
        "command": "-emacs-mcx.executeCommands",
        "when": "editorFocus && findWidgetVisible"
      },
      {
        "key": "right",
        "command": "emacs-mcx.executeCommands",
        "when": "editorFocus && findWidgetVisible && !replaceInputFocussed"
      }, 
```

(and similarly for the rest of the navigation keys)

But, I think this should be the default functionality -- see https://github.com/tuttieee/vscode-emacs-mcx/pull/466.

**Comment by whitphx** [comment] 2021-04-09 16:34
Close this issue due to #466 .

In addition, from version 0.26.0, `emacs-mcx.cursorMoveOnFindWidget` option has been introduced to disable this behavior not only on the replaceWidget but also on the findWidget: https://github.com/whitphx/vscode-emacs-mcx#emacs-mcxcursormoveonfindwidget

**Closed by whitphx** 2021-04-09 16:34 UTC
