### ISSUE TITLE
Keys don't work on find wedget

### ISSUE THREAD

**Issue by makotoshimazu** [whitphx/vscode-emacs-mcx#137] opened 2019-08-06 01:05 UTC
Cursor operations like Ctrl+F/B/A/E and delete like Ctrl+H don't work on Find widget, and moreover, they close the widget.
Is it possible to use them on the widget?

**Comment by ganaware** [comment] 2019-08-06 03:54
There is no way to customize keybindings of input fields:
- microsoft/vscode#65578 Allow to bind cursor navigation keys to input fields
- microsoft/vscode#64694 Allow to configure cursor keys for input fields
- etc: https://github.com/microsoft/vscode/labels/keybindings

(FYI: #55)

**Comment by makotoshimazu** [comment] 2019-08-06 04:49
Thanks for the pointers!
Now I can understand that this is blocked by issues on vscode. I'm going to watch them.

**Comment by makotoshimazu** [comment] 2019-08-06 07:56
And I also found that https://github.com/tuttieee/vscode-emacs-mcx/commit/7da035cf8466ded2958d7c2052157d395383a5f7 is a patch to close the widget.
Now I can understand what's the problem I'm facing with - it closes the widget even when it's replace (not find). I don't have a way to move cursor except for clicking the small input area.

@ganaware Do you have any thoughts?
I personally prefer not closing the widget because currently we can close the find widget by C-g, but we cannot move the cursor during replacing words. (= probably it means reverting [the patch](https://github.com/tuttieee/vscode-emacs-mcx/commit/7da035cf8466ded2958d7c2052157d395383a5f7))

**Comment by ganaware** [comment] 2019-08-06 14:45
I understand that what is the problem.

The patch was introduced by #71  to emulate original i-search behavior, and I think it does good job.

But unwillingly it also affects the replace widget,  because there is no difference between the replace widget and the find widgets.

We have no way to know which widget is visible.
For 'when' clause contexts, VSCode offers "findWidgetVisible" that cannot distinguish them.
( https://code.visualstudio.com/docs/getstarted/keybindings )

So, which is better ?
1. more emacs-like i-search, but poor replace-widget experience. (current)
2. less emacs-like i-search, but cursor movement works.
3. or ...?

**Comment by makotoshimazu** [comment] 2019-08-07 01:54
Given that currently we don't have any keyboard shortcuts to move the cursor, I prefer 2.
I like more emacs-like i-search, but personally bad experience on replace widget seems more problematic than C-g to stop i-search.
What do you think?

**Comment by ganaware** [comment] 2019-08-09 00:29
@tuttieee any ideas?

**Comment by tuttieee** [comment] 2020-03-16 14:14
Sorry, no idea. What @ganaware said is all.
Please override the keybindings by your user-level setting like below as a workaround.

```
{
    "key": "ctrl+f",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+b",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+p",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+n",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+a",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
},
{
    "key": "ctrl+e",
    "command": "-emacs-mcx.executeCommands",
    "when": "editorFocus && findWidgetVisible"
}
```

**Comment by makotoshimazu** [comment] 2020-04-27 00:21
Ah sorry I missed your comments last month.
I have those in my local keybindings.json and I no longer have any problems, but I'd suggest that adding those settings into the default keybindings so that the behavior would be easier to understand (at least for me).
What do you think?

**Comment by tuttieee** [comment] 2020-04-28 16:05
The workaround I provided was to disable closing the find widget - but the disabled behavior here was an intended behavior introduced in #71 as @ganaware said.
So, the workaround here cannot be installed into the default keybindings - it conflicts with the "correct" behavior.

However, there are some options and things to do.
* To write document about this.
* To add the "disabled" version keybindings as an option switchable by config.

Thank you for your suggestion. I will do these things.

**Closed** 2021-02-03 14:34 UTC

**Comment by whitphx** [comment] 2021-02-04 14:11
Now you can use ``emacs-mcx.cursorMoveOnFindWidget`` option with v0.26.0 or later.
